export const commands = [
  { name: 'ban', description: 'Ban a user from the server' },
  { name: 'kick', description: 'Kick a user from the server' },
  { name: 'mute', description: 'Mute a member' },
  { name: 'unmute', description: 'Unmute a member' },
  { name: 'purge', description: 'Bulk delete messages' },
  { name: 'slowmode', description: 'Set slowmode for a channel' },
  { name: 'warn', description: 'Warn a member' },
  { name: 'clearwarns', description: 'Clear all warns for a user' },
  { name: 'lock', description: 'Lock a channel' },
  { name: 'unlock', description: 'Unlock a channel' },
  { name: 'userinfo', description: 'Get info on a user' },
  { name: 'serverinfo', description: 'View server stats' },
  { name: 'avatar', description: 'Get user avatar' },
  { name: 'ping', description: 'Bot latency check' },
  { name: 'uptime', description: 'Show how long the bot has been online' },
  { name: 'say', description: 'Make the bot say something' },
  { name: 'help', description: 'List all commands' },
  { name: 'botinfo', description: 'Get bot stats' },
  { name: 'roleinfo', description: 'Info on a role' },
  { name: 'addrole', description: 'Give a role to user' },
  { name: 'removerole', description: 'Remove a user\'s role' },
  { name: 'emojiinfo', description: 'Get info on emoji' },
  { name: 'nick', description: 'Change user nickname' },
  { name: 'invite', description: 'Bot invite link' },
  { name: 'id', description: 'Get Discord IDs' },
  { name: 'poll', description: 'Create a quick poll' },
  { name: 'quote', description: 'Quote a message' },
  { name: 'reverse', description: 'Reverse a string' },
  { name: 'snipe', description: 'Snipe last deleted message' },
  { name: 'roleall', description: 'Give a role to all users' }
];